### ISSUE TITLE
[main] 공통 프론트 화면 코드 푸쉬

### ISSUE THREAD

**Issue by ddoddo1228** [2024-venture-spring/spring#1]
## 💭 작업 브랜치
> main

## 🍀 기능 설명
> 공통 프론트 코드 업로드

## 🎀 작업 상세 내용
- [x] 웹앱 화면 구현
- [x] 사이드바, 헤더 메뉴, 푸터 구현
- [x] 사이드바 & 모바일 푸터 클릭 시 효과
- [x] 헤더 메뉴 클릭 시 효과 - 홈 화면에만 있게 해뒀는데 바꿔서 구현할 곳으로 가져가세

## 📈 기타
> 가져가서 쓰세요
![image](https://github.com/2024-venture-spring/spring/assets/135615995/bb90aa25-10fe-4961-9d59-42b6862858cd)
![image](https://github.com/2024-venture-spring/spring/assets/135615995/a978c572-ad4e-4812-b0ee-46c137aaca78)

**Comment by ieunseo** [comment]
아유 감사합니다 덕분에 편하게했어요
