### ISSUE TITLE
[feature/mypage] 마이페이지

### ISSUE THREAD

**Issue by ieunseo** [2024-venture-spring/spring#13]
## 💭 작업 브랜치
> feature/mypage

## 🍀 기능 설명
> userNO 가 3 인 친구의 개인정보/ 구매이력을 출력합니다.

## 📈 기타
> 혹시 "빠진내용" 있는지 알려주세용 다른사람들의 리뷰가 필요합니다아아...

**Comment by k168ww** [comment]
위에 #13 이슈 잘못 푸시했습니다 죄송,,, ^^
마이페이지는 구두로 리뷰 완료했습니다.
