### ISSUE TITLE
[feature/admin] repository 주입 문제

### ISSUE THREAD

**Issue by ieunseo** [2024-venture-spring/spring#19]
## 💭 작업 브랜치
> feature/admin

## 🥲 어떤 버그인가요?
>  AdminRepository 클래스를 통해 UserRepository를 주입하기때문에 userRepository 를 찾지못하는 버그

## 📫 어떤 상황에서 발생한 버그인가요?
> userRepository 를 찾지못하여 실행되지않는 버그

## 💸 예상 결과
> 실행시 userrepository 를 찾아 정상작동.

**Comment by k168ww** [comment]
해결완 수고하셨습니당
