### ISSUE TITLE
[feature/admin] DB연결

### ISSUE THREAD

**Issue by ieunseo** [2024-venture-spring/spring#20]
## 💭 작업 브랜치
> feature/admin

## 🍀 기능 설명
> 데이터베이스 연결

## 🎀 작업 상세 내용
- [x] 데이터베이스 연결
- [x] css 수정

## 📈 기타
> 데이터베이스에 group_buying 테이블의 buying_title 날렸습니당 ㅎㅎ

**Comment by k168ww** [comment]
감사합니당
