### ISSUE TITLE
[feature/gonggu] 판매 요청 구현 및 좋아요(?) db연결

### ISSUE THREAD

**Issue by ddoddo1228** [2024-venture-spring/spring#21]
## 💭 작업 브랜치
> [feature/gonggu] 

## 🍀 기능 설명
> 판매 요청 탭 구현 좋아요 구현 및 DB 연결 완료

## 🎀 작업 상세 내용
- [x] 판매 요청 프론트 구현
- [x] 판매 요청 탭 게시글 db연동
- [x] 좋아요(? 저도 사고 싶어요..관심글..?) DB연결

## 📈 기타
> 좋아요 누른 글 DB연결 확인 했습니다. 새로고침 & 재 로그인해도 유지됩니다.
![image](https://github.com/2024-venture-spring/spring/assets/135615995/f2199776-037d-4f1d-b312-0962703be1a2)
![image](https://github.com/2024-venture-spring/spring/assets/135615995/ffb07a3e-da3a-450b-852b-8107c16bef4d)

**Comment by ieunseo** [comment]
좋아요~!
