### ISSUE TITLE
[feature/price] 물가 보여주는 게시판 완성

### ISSUE THREAD

**Issue by syongsyong6035** [2024-venture-spring/spring#22]
## 💭 작업 브랜치
>품목명 입력하면 그거에 해당하는 검색기능도 완성
> 먼저 물가 보여주는 외부api가져오는 건 했습니다

## 🍀 기능 설명
>css를 아직 못했습니다 

## 🎀 작업 상세 내용
- [ ] TODO 검색기능
- [ ] TODO 외부api가져와서 품목으로 나열

## 📈 기타
> 쌀하나여도 마켓이 여러개여서 값이 다다르니까 쌀만 쳐도 한 5개 정도가 나와버리는데 이걸 그냥 대충 하나만 나오게 할지 그냥 마켓이름 보여지게 해서 다보여지게 할지 고민입니다

**Comment by k168ww** [comment]
어느정도의 물가 수준을 보여주는 거니까 저는 하나만 나와도 괜찮을 것 같아요!

**Comment by ieunseo** [comment]
저도 여러개중 하나만 선택해서 나오는거도 괜찮다고 생각해요!

**Comment by syongsyong6035** [comment]
넵 알겟습니당 감사합니다
