### ISSUE TITLE
[feature/price]물가페이지 완성

### ISSUE THREAD

**Issue by syongsyong6035** [2024-venture-spring/spring#25]
## 💭 작업 브랜치
> 물가 페이지 완성

## 🍀 기능 설명
> 날마다 해당하는 물가의 품목명 마켓 가격에 대해 보여줍니다 
>검색기능을 통해 내가 원하는 품목명을 볼수 있습니다 

## 🎀 작업 상세 내용
- [x] 날마다 해당하는 도매가격을 보여준다 
- [x] 근데 api를 가져오는거여서 그런지 들어가는데 한 15초정도 걸리고 들어가진다

**Comment by k168ww** [comment]
ㅋㅋㅋㅋ 느려도 예쁘니까 괜찮아~~
