### ISSUE TITLE
[feature/ohdyo] 신청 & 확인 버튼 기능 구현 마페로 이동

### ISSUE THREAD

**Issue by ohdyo** [2024-venture-spring/spring#40]
## 💭 작업 브랜치
> [feature/ohdyo]

## 🍀 기능 설명
> 신청 확인버튼 가능 중복 안들어감 마페로 이동함

## 🎀 작업 상세 내용
- gongguController에 Post로 메서드 작성해뒀습니다.

**Comment by k168ww** [comment]
수고하셨습니다~~
