### ISSUE TITLE
[feature/mypage] 마이페이지 수정

### ISSUE THREAD

**Issue by ddoddo1228** [2024-venture-spring/spring#6]
## 💭 작업 브랜치
> [feature/mypage]

## 🍀 기능 설명
> 마이페이지 수정

## 🎀 작업 상세 내용
- [x] 웹앱으로 수정
- [x] 폼 수정

## 📈 기타
> 참고사항, 설명, 스크린샷 등 자유롭게 올려주세요
![image](https://github.com/2024-venture-spring/spring/assets/135615995/5f820160-ab0f-4597-900a-84620037c896)
![image](https://github.com/2024-venture-spring/spring/assets/135615995/dfd7dea5-0094-4fde-b0a2-bc48104dacd7)

**Comment by ieunseo** [comment]
아유 덕분에 편하게했습니다 감사합니다
